apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
    #targetPort: 80 (Caso somente o port seja especificado, subentende que o tagetPort é igual ao port)
      nodePort: 30000
  selector:
    app: primeiro-pod
